name: bee_env
channels:
  - apple
  - conda-forge
dependencies:
  - absl-py=0.10.0=pyhd8ed1ab_1
  - aiohttp=3.8.3=py39h02fc5c5_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - altgraph=0.17.2=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - blinker=1.5=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h02fc5c5_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cryptography=38.0.2=py39haa0b8cc_2
  - freetype=2.12.1=hd633e50_0
  - frozenlist=1.3.1=py39h02fc5c5_1
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=h27ca646_2
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.49.1
  - h5py=3.1.0=nompi_py39h99babb8_100
  - hdf5=1.10.6=nompi_h0fc092c_1114
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.0.0=pyha770c72_1
  - jpeg=9e=he4db4b2_2
  - keras=2.6.0=pyhd8ed1ab_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - krb5=1.19.3=hf9b2bbe_0
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libabseil=20220623.0=cxx17_h28b99d4_4
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libclang=11.1.0=default_h0fdd720_1
  - libcurl=7.86.0=hd538317_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.10=h3422bc3_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_25
  - libgfortran5=11.3.0=hdaf2cc0_25
  - libgrpc=1.49.1
  - liblapack=3.9.0=16_osxarm64_openblas
  - libllvm11=11.1.0=hfa12f05_5
  - libnghttp2=1.47.0=h232270b_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.38=h76d750c_0
  - libprotobuf=3.21.9=hb5ab8b9_0
  - libsqlite=3.39.4=h76d750c_0
  - libssh2=1.10.0=hb80f160_3
  - libtiff=4.3.0=h2810ee2_4
  - libwebp=1.2.2=h0d20362_0
  - libwebp-base=1.2.2=h3422bc3_1
  - libxcb=1.13=h9b22ae9_1004
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=14.0.4=hd125106_0
  - macholib=1.16.2=pyhd8ed1ab_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h02fc5c5_2
  - multidict=6.0.2=py39h02fc5c5_2
  - ncurses=6.3=h07bb92c_1
  - numpy=1.19.5=py39h54e5778_3
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=hd370e0e_0
  - openssl=1.1.1q=h03a7124_1
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - pillow=9.0.1=py39hd72dd6b_2
  - pip=22.3=pyhd8ed1ab_0
  - protobuf=4.21.9=py39h23fbdae_0
  - pthread-stubs=0.4=h27ca646_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyinstaller-hooks-contrib=2022.11=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.10=hd16f9c5_2_cpython
  - python_abi=3.9=2_cp39
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2022.06.01=h9a09cb3_0
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scipy=1.9.1=py39h737da60_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.39.4=h2229b38_0
  - tensorboard=2.6.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py39haa0b8cc_3
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow-deps=2.6.0=0
  - termcolor=1.1.0=pyhd8ed1ab_3
  - tk=8.6.12=he1e0b03_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2022e=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - wrapt=1.12.1=py39h5161555_3
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yarl=1.8.1=py39h02fc5c5_0
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
    - clang==5.0
    - flatbuffers==1.12
    - ftfy==6.1.1
    - pyinstaller==5.2
    - regex==2022.9.13
    - tensorflow-estimator==2.10.0
    - tensorflow-macos==2.6.0
    - tensorflow-metal==0.1.2
    - tqdm==4.64.1
    - wcwidth==0.2.5
